"""Constants."""

from homeassistant.components.alarm_control_panel import (
    DOMAIN as ALARM_CONTROL_PANEL_DOMAIN,
)
from homeassistant.components.binary_sensor import DOMAIN as BINARY_SENSOR_DOMAIN
from homeassistant.components.cover import DOMAIN as COVER_DOMAIN
from homeassistant.components.fan import DOMAIN as FAN_DOMAIN
from homeassistant.components.light import DOMAIN as LIGHT_DOMAIN
from homeassistant.components.lock import DOMAIN as LOCK_DOMAIN
from homeassistant.components.sensor import DOMAIN as SENSOR_DOMAIN
from homeassistant.components.switch import DOMAIN as SWITCH_DOMAIN
from homeassistant.components.template.const import (
    CONF_ATTRIBUTE_TEMPLATES,
    CONF_ATTRIBUTES,
    CONF_AVAILABILITY,
    CONF_AVAILABILITY_TEMPLATE,
    CONF_PICTURE,
)
from homeassistant.components.template.cover import CONF_POSITION, CONF_TILT
from homeassistant.components.template.fan import (
    CONF_DIRECTION,
    CONF_OSCILLATING,
    CONF_PERCENTAGE,
    CONF_PRESET_MODE,
)
from homeassistant.components.template.light import (
    CONF_EFFECT_LIST,
    CONF_HS,
    CONF_HS_ACTION,
    CONF_LEVEL,
    CONF_MAX_MIREDS,
    CONF_MIN_MIREDS,
    CONF_RGB,
    CONF_RGBW,
    CONF_RGBWW,
    CONF_SUPPORTS_TRANSITION,
    CONF_TEMPERATURE,
    CONF_WHITE_VALUE,
)
from homeassistant.components.template.lock import CONF_CODE_FORMAT
from homeassistant.components.template.vacuum import CONF_BATTERY_LEVEL, CONF_FAN_SPEED
from homeassistant.components.template.weather import (
    CONF_APPARENT_TEMPERATURE,
    CONF_ATTRIBUTION,
    CONF_CLOUD_COVERAGE,
    CONF_CONDITION,
    CONF_DEW_POINT,
    CONF_FORECAST_DAILY,
    CONF_FORECAST_HOURLY,
    CONF_FORECAST_TWICE_DAILY,
    CONF_HUMIDITY,
    CONF_OZONE,
    CONF_PRESSURE,
    CONF_UV_INDEX,
    CONF_VISIBILITY,
    CONF_WIND_BEARING,
    CONF_WIND_GUST_SPEED,
    CONF_WIND_SPEED,
)
from homeassistant.components.vacuum import DOMAIN as VACUUM_DOMAIN
from homeassistant.components.weather import DOMAIN as WEATHER_DOMAIN
from homeassistant.const import (
    CONF_EFFECT,
    CONF_ENTITY_PICTURE_TEMPLATE,
    CONF_FRIENDLY_NAME,
    CONF_FRIENDLY_NAME_TEMPLATE,
    CONF_ICON,
    CONF_ICON_TEMPLATE,
    CONF_NAME,
    CONF_STATE,
    CONF_VALUE_TEMPLATE,
)

DOMAIN = "template_migration"

# Legacy Actions
CONF_COLOR_ACTION = "set_color"

# Legacy Fields
CONF_APPARENT_TEMPERATURE_TEMPLATE = "apparent_temperature_template"
CONF_ATTRIBUTION_TEMPLATE = "attribution_template"
CONF_BATTERY_LEVEL_TEMPLATE = "battery_level_template"
CONF_CLOUD_COVERAGE_TEMPLATE = "cloud_coverage_template"
CONF_CODE_FORMAT_TEMPLATE = "code_format_template"
CONF_COLOR_TEMPLATE = "color_template"
CONF_CONDITION_TEMPLATE = "condition_template"
CONF_DEW_POINT_TEMPLATE = "dew_point_template"
CONF_DIRECTION_TEMPLATE = "direction_template"
CONF_EFFECT_LIST_TEMPLATE = "effect_list_template"
CONF_EFFECT_TEMPLATE = "effect_template"
CONF_FAN_SPEED_TEMPLATE = "fan_speed_template"
CONF_FORECAST_DAILY_TEMPLATE = "forecast_daily_template"
CONF_FORECAST_HOURLY_TEMPLATE = "forecast_hourly_template"
CONF_FORECAST_TWICE_DAILY_TEMPLATE = "forecast_twice_daily_template"
CONF_HS_TEMPLATE = "hs_template"
CONF_HUMIDITY_TEMPLATE = "humidity_template"
CONF_LEVEL_TEMPLATE = "level_template"
CONF_MAX_MIREDS_TEMPLATE = "max_mireds_template"
CONF_MIN_MIREDS_TEMPLATE = "min_mireds_template"
CONF_OSCILLATING_TEMPLATE = "oscillating_template"
CONF_OZONE_TEMPLATE = "ozone_template"
CONF_PERCENTAGE_TEMPLATE = "percentage_template"
CONF_POSITION_TEMPLATE = "position_template"
CONF_PRESET_MODE_TEMPLATE = "preset_mode_template"
CONF_PRESSURE_TEMPLATE = "pressure_template"
CONF_RGB_TEMPLATE = "rgb_template"
CONF_RGBW_TEMPLATE = "rgbw_template"
CONF_RGBWW_TEMPLATE = "rgbww_template"
CONF_SUPPORTS_TRANSITION_TEMPLATE = "supports_transition_template"
CONF_TEMPERATURE_TEMPLATE = "temperature_template"
CONF_TEMPERATURE_TEMPLATE = "temperature_template"
CONF_TILT_TEMPLATE = "tilt_template"
CONF_UV_INDEX_TEMPLATE = "uv_index_template"
CONF_VISIBILITY_TEMPLATE = "visibility_template"
CONF_WHITE_VALUE_TEMPLATE = "white_value_template"
CONF_WIND_BEARING_TEMPLATE = "wind_bearing_template"
CONF_WIND_GUST_SPEED_TEMPLATE = "wind_gust_speed_template"
CONF_WIND_SPEED_TEMPLATE = "wind_speed_template"

COMMON_LEGACY_FIELDS = {
    CONF_ICON_TEMPLATE: CONF_ICON,
    CONF_ENTITY_PICTURE_TEMPLATE: CONF_PICTURE,
    CONF_AVAILABILITY_TEMPLATE: CONF_AVAILABILITY,
    CONF_ATTRIBUTE_TEMPLATES: CONF_ATTRIBUTES,
    CONF_FRIENDLY_NAME: CONF_NAME,
}

LEGACY_KEYS = {
    ALARM_CONTROL_PANEL_DOMAIN: "panels",
    BINARY_SENSOR_DOMAIN: "sensors",
    COVER_DOMAIN: "covers",
    FAN_DOMAIN: "fans",
    LIGHT_DOMAIN: "lights",
    LOCK_DOMAIN: None,
    SENSOR_DOMAIN: "sensors",
    SWITCH_DOMAIN: "switches",
    VACUUM_DOMAIN: "vacuums",
    WEATHER_DOMAIN: None,
}

LEGACY_FIELDS = {
    ALARM_CONTROL_PANEL_DOMAIN: {
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    BINARY_SENSOR_DOMAIN: {
        CONF_FRIENDLY_NAME_TEMPLATE: CONF_NAME,
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    COVER_DOMAIN: {
        CONF_VALUE_TEMPLATE: CONF_STATE,
        CONF_POSITION_TEMPLATE: CONF_POSITION,
        CONF_TILT_TEMPLATE: CONF_TILT,
    },
    FAN_DOMAIN: {
        CONF_DIRECTION_TEMPLATE: CONF_DIRECTION,
        CONF_OSCILLATING_TEMPLATE: CONF_OSCILLATING,
        CONF_PERCENTAGE_TEMPLATE: CONF_PERCENTAGE,
        CONF_PRESET_MODE_TEMPLATE: CONF_PRESET_MODE,
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    LIGHT_DOMAIN: {
        CONF_COLOR_ACTION: CONF_HS_ACTION,
        CONF_COLOR_TEMPLATE: CONF_HS,
        CONF_EFFECT_LIST_TEMPLATE: CONF_EFFECT_LIST,
        CONF_EFFECT_TEMPLATE: CONF_EFFECT,
        CONF_HS_TEMPLATE: CONF_HS,
        CONF_LEVEL_TEMPLATE: CONF_LEVEL,
        CONF_MAX_MIREDS_TEMPLATE: CONF_MAX_MIREDS,
        CONF_MIN_MIREDS_TEMPLATE: CONF_MIN_MIREDS,
        CONF_RGB_TEMPLATE: CONF_RGB,
        CONF_RGBW_TEMPLATE: CONF_RGBW,
        CONF_RGBWW_TEMPLATE: CONF_RGBWW,
        CONF_SUPPORTS_TRANSITION_TEMPLATE: CONF_SUPPORTS_TRANSITION,
        CONF_TEMPERATURE_TEMPLATE: CONF_TEMPERATURE,
        CONF_VALUE_TEMPLATE: CONF_STATE,
        CONF_WHITE_VALUE_TEMPLATE: CONF_WHITE_VALUE,
    },
    LOCK_DOMAIN: {
        CONF_CODE_FORMAT_TEMPLATE: CONF_CODE_FORMAT,
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    SENSOR_DOMAIN: {
        CONF_FRIENDLY_NAME_TEMPLATE: CONF_NAME,
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    SWITCH_DOMAIN: {
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    VACUUM_DOMAIN: {
        CONF_BATTERY_LEVEL_TEMPLATE: CONF_BATTERY_LEVEL,
        CONF_FAN_SPEED_TEMPLATE: CONF_FAN_SPEED,
        CONF_VALUE_TEMPLATE: CONF_STATE,
    },
    WEATHER_DOMAIN: {
        CONF_APPARENT_TEMPERATURE_TEMPLATE: CONF_APPARENT_TEMPERATURE,
        CONF_ATTRIBUTION_TEMPLATE: CONF_ATTRIBUTION,
        CONF_CLOUD_COVERAGE_TEMPLATE: CONF_CLOUD_COVERAGE,
        CONF_CONDITION_TEMPLATE: CONF_CONDITION,
        CONF_DEW_POINT_TEMPLATE: CONF_DEW_POINT,
        CONF_FORECAST_DAILY_TEMPLATE: CONF_FORECAST_DAILY,
        CONF_FORECAST_HOURLY_TEMPLATE: CONF_FORECAST_HOURLY,
        CONF_FORECAST_TWICE_DAILY_TEMPLATE: CONF_FORECAST_TWICE_DAILY,
        CONF_HUMIDITY_TEMPLATE: CONF_HUMIDITY,
        CONF_OZONE_TEMPLATE: CONF_OZONE,
        CONF_PRESSURE_TEMPLATE: CONF_PRESSURE,
        CONF_TEMPERATURE_TEMPLATE: CONF_TEMPERATURE,
        CONF_UV_INDEX_TEMPLATE: CONF_UV_INDEX,
        CONF_VISIBILITY_TEMPLATE: CONF_VISIBILITY,
        CONF_WIND_BEARING_TEMPLATE: CONF_WIND_BEARING,
        CONF_WIND_GUST_SPEED_TEMPLATE: CONF_WIND_GUST_SPEED,
        CONF_WIND_SPEED_TEMPLATE: CONF_WIND_SPEED,
    },
}
